### ISSUE TITLE
Составление ТЗ и плана работ

### ISSUE THREAD

**Issue by evgeny-p** [iv522-sibsutis/password-generator#1]
Примерное содержание ТЗ доступно в [статье](http://evgeny-p.github.io/teaching/materials/project/02-planning.html).

Definition of Done:
1. В [wiki](https://github.com/iv522-sibsutis/password-generator/wiki) проекта написана статья с ТЗ.
2. В [issues](https://github.com/iv522-sibsutis/password-generator/issues) созданы задачи.
3. ТЗ и план приняты заказчиком.

По готовности оставить комментарий в этой задаче.

**Comment by DSG888** [comment]
Построение архитектуры программы

Парсинг передаваемых аргументов
Функция вывода в терминал
Функция генерации случайных символов

Разработка GUI

Оптимизация

Тестирование

Компиляция
Компоновка инсталлятора/пакета

Написание документации

**Comment by evgeny-p** [comment]
1. Список под заголовком «Специальные требования» фактически описывает функциональные требования. Можно объединить с соответствующим разделом.
2. Как зависимость приложения от внешних библиотек связана с надежностью?
3. > Построение архитектуры программы
   
   Поясните, пожалуйста, какой артефакт ожидается получить в результате выполнения задачи?
4. > Оптимизация
   
   Оптимизация имеет смысл в случае обнаружения в приложении тонких мест. Заводить такую задачу на этапе планирования — преждевременно.
5. > Компиляция
   
   Что ожидается получить в результате выполнения задачи?

Оформление статьи обсуждали устно, продублирую сюда:
1. Значительная часть текста по смыслу представляет собой списки, но оформлена как код. Нужно переверстать.
2. В конце заголовков двоеточие/точка не ставятся.

**Comment by DSG888** [comment]
Обновление 2016.03.21:

Построение структуры программы

Парсинг передаваемых аргументов
Функция вывода в терминал
Функция генерации случайных символов
Функция проверки сгенерированных паролей

Разработка GUI

Тестирование

Компиляция под WinNT
Компоновка инсталлятора/пакета

Написание документации

**Comment by evgeny-p** [comment]
Предложенные задачи можно оформлять в виде отдельных issues.

По ТЗ. В чате обсуждали, что независимость от внешних библиотек характеризует переносимость приложения, а не его надежность.

**Comment by evgeny-p** [comment]
У задач есть поле Assignee, пользуйтесь им для назначения задачи исполнителю.
